### ISSUE TITLE
improve support to auto-doc markup

### ISSUE THREAD

**Issue by concon121** [sphinx-contrib/sphinxcontrib-confluencebuilder#51] opened 2017-10-03 15:53 UTC
The resulting documentation better suits a markdown processor, on Confluence its just not rendered correctly.

For example:

<pre>
**strong** should be *strong*
``italics`` should be _italics_
</pre>

It would also be nice for the class definition to be a heading rather than bold, and pages to be children of the index.

**Comment by jdknight** [comment] 2017-10-07 21:15
@concon121, just for clarifications on some things.

I don't think I understand your example correctly. For `**strong** should be *strong*`, I believe this extension handles the [strong emphasis markup](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#strong-emphasis) correctly. The string `This is **strong text**.` [(ref)](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blame/master/test/validation-set/inline-markup.rst#L17) is translated to `This is *strong text*.` in (at least my) the Wiki translation. The [Atlassian Cloud instance I test with](https://jdknight.atlassian.net/wiki/x/1ewE) shows the text as strong. Is there something else you're observing with the strong markup?

To continue with your example, I don't believe the value ` ``italics`` ` should be treated as italic (emphasized) text. In reStructuredText, I would expect it to be translated to an [inline literal](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-literals).

In relation to this, there is a pending change to be reviewed (#53) which adjusts the [interpreted text markup](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text) to be italic looking, instead of boldface looking. This is mimic the same visual presentation which Sphinx's html builder presents. The specification does state that "text itself is typically left alone", so who knows if it's the right choice to boldface it. See the commit  'wiki-translator: emphasize title references' 93802a350efe945fd8398008712662b36965c725.

As for your last comment, you mention that "the class definition to be a heading rather than bold". I'm assuming you referring to reStructuredText's [class markup](http://docutils.sourceforge.net/docs/ref/rst/directives.html#class)? Hopefully next pass it will be looked at (ideally, hoping to go through the entire reStructuredText directives and compiling at list of what's supported, partially supported and not yet supported).

Also, for you last comment "pages to be children of the index" (just to be clear) are you looking to have a Sphinx `master_doc` defined page to be a container for all generated pages? While it could be possible, some additional investigate would need to be done. For now, with the supported space/parent page placements and some prospect hierarchy support (see #35), it would be nice to ensure future work related to page organization is integrated well to ensure existing functionality and this new (and other page restructuring) works gracefully. Thanks for the recommendation.

**Comment by concon121** [comment] 2017-10-08 07:13
Sorry if I was a little vague, I literally only just started using sphinx so im still learning the ropes!

Basically, i'm using sphinx-autodoc to generate documentation from my docstrings in the code, then using sphinxcontrib-confluencebuilder to upload the output of autodoc to my companies cloud Confluence instance.

I'm observing content being uploaded to Confluence displaying rendered on the screen as the example below:

<pre>
*class my_module.MyClass*
Bases: ``object``
*a_method(args)*
</pre>

Based on your response, my guess is that the autodoc generated files are not being converted into confluence wiki markup?

**Comment by jdknight** [comment] 2017-10-08 17:12
It is most likely the case that this extension isn't performing the conversion correctly. It was only recently since we've supported a more extensive reference (link) and TOC support. I would imagine using `sphinx-autodoc` would be producing proper markup and it's generated markup which isn't fully supported by this extension. I haven't used autodoc before, but I'll try to make an attempt to try it out when there's time to work on reStructuredText's miscellaneous and Sphinx domain-specific markup.

**Comment by eikonomega** [comment] 2017-11-28 15:15
Hello @jdknight.  Thanks so much for your efforts to build/maintain this library.  

AutoDoc is an awesome extension to Sphinx that generates documention from properly formatted docstrings in your code.

I can confirm that some of the output is not being translated correctly in this plugin.  Here are a couple of visual examples of what happens.

When using the `make html` command and autodoc you will end up with something that looks like this...
![image](https://user-images.githubusercontent.com/415939/33327040-8ac6fe46-d424-11e7-9423-9736e81b98e8.png)

However, when you use the `make confluence` command, what you get in the wiki isn't correct and ends up looking like this...

![image](https://user-images.githubusercontent.com/415939/33327054-921dcd5a-d424-11e7-9f87-2c476f42923b.png)

I'd be happy to help add this support if you'd like to collaborate.

Cheers.

**Comment by jdknight** [comment] 2017-12-05 07:04
@eikonomega, contributions are welcome. I'd be happy to review any pull requests you're willing to submit (if you do, please include the sign-off meta). Anything "standard"/common with Sphinx documentation to work with Confluence will most likely be accepted (assuming the code is good 😄). I would think AutoDoc would be an acceptable support case; however, note that any significant changes will have to go through @tonybaloney for approval.

If you want to work on providing this capability together, I don't mind having some back-and-forth. The biggest thing I see is getting a proper example set to work with. Note that my "active" priority is to first focus on #35 -- it's been on the back-burner way to long. That being said, don't let that stop you from starting to code and/or provide some example sets you would think would be good.

I would feel a good end goal would include:
- The code to actually support AutoDoc content.
- Test code/assets to help validate a standard/expected set of documentation.
- Documentation for any special configurations, if required, to process an AutoDoc-documentation set.

----

I'd also be curious about the generated results now that v0.7 has been released. Not that it will generate the ideal visualization for an AutoDoc project, but I believe there has been some improvement to definition types (so it might not look as bad).

**Comment by jdknight** [comment] 2018-07-24 05:38
An update.

The branch `feature/storage-format-conversion` provides some improved autodoc support. In time, the feature will be reviewed and (hopefully) merged in (no timeline or target version is set). For the bold, the branch can be checked out and tested with (with the note that this is pre-reviewed implementation).

**Comment by jdknight** [comment] 2018-08-06 06:30
The storage format improvements are now available on `master` (for those who would like to try).

I will be marking this issue as pending-next-release and will leave open until these changes are made available in `pip`.

For any individual who may try autodoc capabilities with these changes and observed unexpected issues, you may provide this feedback in this issue. However, in the event that the storage format changes included in the next release, this issue will be marked as closed; any issues related to autodoc should then be created in their own issues with more specific details on what examples are failing with autodoc.

**Comment by caturday** [comment] 2019-01-30 16:31
Thanks for putting in this fix. I'd like to be able to take advantage of it - any plans yet for release of 0.10?

**Comment by jdknight** [comment] 2019-03-15 06:34
Version 1.0 of this extension has been released with this change; closing this issue.

**Closed by jdknight** 2019-03-15 06:34 UTC
Labels: enhancement
